language: generic
os:
  - linux

env:
  - FORTRANDIR="$(pwd)/DIVA3D/src/Fortran/" DIVADIR="$(pwd)/DIVA3D/divastripped/"

sudo: required
addons:
    apt: # apt-get for linux
        packages:
          - libhdf5-serial-dev
          - libnetcdf-dev
          - libnetcdff-dev
          - netcdf-bin
          - gfortran

install:
  - echo "Source directory --> ${FORTRANDIR}"
  - echo "DIVA directory --> ${DIVADIR}"

before_script:
  - export PATH=${PATH}:.

script:
  - cd ${FORTRANDIR}; make clean; make
  - cd ${DIVADIR}; ./divatest0
