name: DIVA compilation
on: [push]
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get install -y wget make gfortran netcdf-bin libnetcdf-dev libnetcdff-dev
      - name: Download DIVA
        env:
          DIVA_VERSION: 4.7.2
          TOOLSDIR: "/tmp/tools/"
        run: |
          echo "Installing DIVA software"
          mkdir -pv ${TOOLSDIR}
          cd ${TOOLSDIR}
          wget -q "https://github.com/gher-uliege/DIVA/archive/refs/tags/v${DIVA_VERSION}.tar.gz"
          tar xvf "v${DIVA_VERSION}.tar.gz"
      - name: Compilation
        env:
          DIVA_VERSION: 4.7.2
          TOOLSDIR: "/tmp/tools/"
        run: |
          cd ${TOOLSDIR}/DIVA-${DIVA_VERSION}/DIVA3D/src/Fortran/
          make
      - name: Test code
        env:
          DIVA_VERSION: 4.7.2
          TOOLSDIR: "/tmp/tools/"
        run: |
          export PATH=.:${PATH}
          echo "This is the PATH variable: ${PATH}"
          cd ${TOOLSDIR}/DIVA-${DIVA_VERSION}/DIVA3D/divastripped/
          ./divatest0
