name: DIVA compilation
on: [push]
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get install -y make gfortran netcdf-bin libnetcdf-dev libnetcdff-dev
      - name: Download DIVA
        run: echo "Installing DIVA software"
